defaults: &defaults
  working_directory: ~/pawa

version: 2
jobs:
  build:
    <<: *defaults
    docker:
        - image: circleci/openjdk:11-jdk
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - pawa-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - pawa-
      - run: mvn -B de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
      - run: mvn test
      - save_cache:
          paths:
            - ~/.m2
          key: pawa-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - target

  coverage:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:curl
    steps:
        - checkout
        - attach_workspace:
            at: ~/pawa
        - run: bash <(curl -s https://codecov.io/bash) -s ~/pawa/target -X gcov

  package:
    <<: *defaults
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - pawa-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - pawa-
      - attach_workspace:
          at: ~/pawa
      - run: |
          [[ -v CIRCLE_TAG ]] && VERSION=${CIRCLE_TAG#"v"} || VERSION=${CIRCLE_BUILD_NUM}
          mvn package -B -Dtimestamp=$(date -u +%FT%TZ) -Dversion=${VERSION} -Drevision=$(git rev-parse --short HEAD)
          zip -r -9 -q /tmp/throw-voice.zip target/throw-voice-release
      - store_artifacts:
          path: /tmp/throw-voice.zip

  container:
    <<: *defaults
    machine: true
    steps:
      - checkout
      - run: |
          VCS_REF=$(git rev-parse --short HEAD)
          [[ -v CIRCLE_TAG ]] && VERSION=${CIRCLE_TAG#"v"} || VERSION=1.2.0-beta.${CIRCLE_BUILD_NUM}
          BUILD_DATE=$(date -u +%FT%TZ)
          docker build --quiet --cache-from gdragon/throw-voice:latest -t gdragon/throw-voice:${VERSION} -t gdragon/throw-voice:latest --build-arg VCS_REF=${VCS_REF} --build-arg BUILD_DATE=${BUILD_DATE} --build-arg VERSION=${VERSION} .
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          docker push gdragon/throw-voice:${VERSION}
          [[ -v CIRCLE_TAG ]] && docker push gdragon/throw-voice:latest || true

workflows:
  version: 2
  build-with-coverage-and-docker-deploy:
    jobs:
      - build
      - coverage:
          requires:
            - build
      - package:
          requires:
            - build
          filters:
            branches:
              only: /.*/
      - container:
          requires:
            - build
          filters:
            branches:
              only: master
