defaults: &defaults
  working_directory: ~/pawa

version: 2
jobs:
  build:
    <<: *defaults
    docker:
        - image: circleci/openjdk:9-jdk
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - pawa-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - pawa-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: pawa-{{ checksum "pom.xml" }}
      - run: mvn integration-test
      - persist_to_workspace:
          root: .
          paths:
            - target

  coverage:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:curl
    steps:
        - checkout
        - attach_workspace:
            at: ~/pawa
        - run: bash <(curl -s https://codecov.io/bash) -s ~/pawa/target -X gcov

  upload-artifact:
    <<: *defaults
    machine: true
    steps:
      - attach_workspace:
          at: ~/pawa
      - store_artifacts:
          path: target/throw-voice-1.2.0-SNAPSHOT-release.zip

  container:
    <<: *defaults
    machine: true
    steps:
      - checkout
      - run: |
          VCS_REF=$(git rev-parse --short HEAD)
          [[ -v CIRCLE_TAG ]] && VERSION=${CIRCLE_TAG} || VERSION=1.2.0.${CIRCLE_BUILD_NUM}
          BUILD_DATE=$(date +%FT%T.%z)
          echo ${VERSION}
          # docker build --quiet --cache-from gdragon/throw-voice:latest -t gdragon/throw-voice:${VERSION} --build-arg VCS_REF=${VCS_REF} --build-arg BUILD_DATE=${BUILD_DATE} --build-arg VERSION=${VERSION} .
          # docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          # docker push gdragon/throw-voice:${VERSION}

workflows:
  version: 2
#  build-with-coverage:
#    jobs:
#      - build
#      - coverage:
#          requires:
#            - build
#      - upload-artifact:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
  build-container-deploy:
    jobs:
      - container
